### ISSUE TITLE
Collect all Issues that regard Architecture from the Backlog

### ISSUE THREAD

**Issue by NikitaHans** [mobileappdevhm/dev-team-4-cie-app-ios-swift#1]
Use the given [Backlog](https://github.com/mobileappdevhm/CiEApp/wiki/Product-Backlog) to identify all issues that you see fit/necessary to be included in our iOS CiE Application.
Add all issues that regard the architecture in a list on this [wiki page](https://github.com/mobileappdevhm/dev-team-4-cie-app-ios-swift/wiki/Refinement-Lists)

Do not create issues in our project.
Do not disregard questionable Issues we will handle them sort them out later.

**Comment by Sneckl** [comment]
All issues are collected.
