### ISSUE TITLE
Functionality and flow across different pages 

### ISSUE THREAD

**Issue by jackty9** [mobileappdevhm/dev-team-4-cie-app-ios-swift#15]
Page 1 : Log in 

- [ ] Username and password - upon successful credentials will link to Settings page, where user profile, tracking of ECTS and courses taken are shown

- [ ] Forgot password - lead to pages where users can reset password

- [ ] To discuss - To log in without an account

Page 2 : Course List

- [ ] Show big tiles displaying respective departments

- [ ] When clicked, should display a list tiles displaying courses

- [ ]  Each course tile should have an overview of title, time, campus location and ECTS points

- [ ] Each course tile should be expandable to show more details - course description, lecturers' details etc

- [ ] When hit on the "love" icon, courses will be added into page 5 - Favorites

Page 3 : Maps

- [ ] display maps which links to Google Maps when clicked 

Page 4 : Timetable

- [ ] Daily timetable

- [ ] Weekly timetable 

Page 5 : Favorites

- [ ] List of favorite-ed courses from page 2

- [ ] "warning" at the bottom for possible conflicts between courses 

- [ ] Submit button for submission 

Page 6 : Settings

- [ ] display of registered users

- [ ] "Progress bar" for accumulated ECTS points

- [ ] List of taken courses

**Comment by NikitaHans** [comment]
This has been added as a [wikipage](https://github.com/mobileappdevhm/dev-team-4-cie-app-ios-swift/wiki/Horizontal-based-behaviour-description)
