### ISSUE TITLE
Implement FavoritesViewController

### ISSUE THREAD

**Issue by NikitaHans** [mobileappdevhm/dev-team-4-cie-app-ios-swift#30]
- Display the users favourite lectures in a tableView
- Add a button for submitting chosen courses (place it somewhere convenient)
- Add Option to check time conflicts (implement as you see fit how to respond (ONLY UI) ) or a warning banner
- Display current aggregated ECT's
- Show current CiE certificate progress state

**Comment by Sneckl** [comment]
Hello Nikita,
nice view.
But I cannot find "Display current aggregated ECT's" as it is described in this issue.
