### ISSUE TITLE
Create a Login Screen View

### ISSUE THREAD

**Issue by NikitaHans** [mobileappdevhm/dev-team-4-cie-app-ios-swift#47]
Create a Login Screen View (Storyboard)
Create a Login Screen Controller
Create a Login Screen Model

Implement a Login Screen Protocol

**Comment by jackty9** [comment]
finished and committed to branch/feature/47-Login-Screen-Vie

**Comment by NikitaHans** [comment]
Here is a link to your [PR](https://github.com/mobileappdevhm/dev-team-4-cie-app-ios-swift/pull/52) please see the review and fix accordingly.
